### ISSUE TITLE
Fdroid repo not updating 

### ISSUE THREAD

**Issue by cd0rw0** [j2ghz/FDroid-Data#1]
hi , 

Last few days fdroid repo not updating & getting "error getting index file" message. 

Regards

**Comment by j2ghz** [comment]
I am looking into that, it seems that a new version of FDroid client uses index.json instead of xml, so I have to update my fdroid server

**Comment by j2ghz** [comment]
https://gitlab.com/fdroid/fdroidserver/issues/310

**Comment by j2ghz** [comment]
It seems the issue is elsewhere: https://gitlab.com/fdroid/fdroidclient/issues/1040

**Comment by cd0rw0** [comment]
wow look like bigger issue then i assume earlier. 
i assumed it should be just small typo error since there was update few days ago.

**Comment by j2ghz** [comment]
If you don't want to wait you can get F-Droid client version 0.100 which works (I haven't tested other versions). It seems to me the new version doesn't like my SSL certificate, which I got from CloudFlare so there should be no problem.

**Comment by cd0rw0** [comment]
im not complaining on being late getting resolved or anything or anything, just saying i assumed i will be simple thing but look like f-droid client need an update which i think defiantly will take some time.

i already install 0.100 after read your report here  https://gitlab.com/fdroid/fdroidclient/issues/1040

**Comment by j2ghz** [comment]
@cd0rw0 👍 
https://gitlab.com/fdroid/fdroidclient/issues/1040 It's a relief I'm not the only one with that issue

**Comment by j2ghz** [comment]
It's fixed. https://gitlab.com/fdroid/fdroidclient/issues/1040#note_30975303
